// Маппинг названий блюд к файлам изображений из personal-chef-meals-kandinsky-prompts.md
// Формат: название блюда -> путь к изображению
export const mealImageMapping: Record<string, string> = {
  // ХОЛОДНЫЕ БЛЮДА (25)
  'Татар из сёмги с авокадо': '/images/meals/tartar-syomga-avokado.jpg',
  'Салат Цезарь с курицей и пармезаном': '/images/meals/caesar-salad-chicken-parmesan.jpg',
  'Греческий салат с фетой': '/images/meals/greek-salad-feta.jpg',
  'Тартар из говядины с яичным желтком': '/images/meals/beef-tartar-egg-yolk.jpg',
  'Салат с тунцом и авокадо': '/images/meals/tuna-avocado-salad.jpg',
  'Карпаччо из телятины': '/images/meals/veal-carpaccio.jpg',
  'Салат из морепродуктов': '/images/meals/seafood-salad.jpg',
  'Салат с креветками и авокадо': '/images/meals/shrimp-avocado-salad.jpg',
  'Оливье кето-версия': '/images/meals/keto-olivier.jpg',
  'Салат с курицей и орехами': '/images/meals/chicken-nut-salad.jpg',
  'Тартар из лосося с огурцом': '/images/meals/salmon-tartar-cucumber.jpg',
  'Салат с индейкой и сыром': '/images/meals/turkey-cheese-salad.jpg',
  'Цезарь с лососем': '/images/meals/caesar-salmon.jpg',
  'Салат с яйцами и беконом': '/images/meals/egg-bacon-salad.jpg',
  'Гуакамоле с овощами': '/images/meals/guacamole-vegetables.jpg',
  'Салат с кальмарами': '/images/meals/squid-salad.jpg',
  'Салат с мидиями': '/images/meals/mussel-salad.jpg',
  'Салат с крабом и авокадо': '/images/meals/crab-avocado-salad.jpg',
  'Салат с печенью и овощами': '/images/meals/liver-vegetable-salad.jpg',
  'Салат с баклажанами и сыром': '/images/meals/eggplant-cheese-salad.jpg',
  'Салат с копченой курицей': '/images/meals/smoked-chicken-salad.jpg',
  'Салат с говядиной и рукколой': '/images/meals/beef-arugula-salad.jpg',
  'Салат с яйцами пашот': '/images/meals/poached-egg-salad.jpg',
  'Салат с грибами и сыром': '/images/meals/mushroom-cheese-salad.jpg',
  'Винегрет с селедкой': '/images/meals/herring-vinaigrette.jpg',
  
  // ГОРЯЧИЕ ПЕРВЫЕ (25)
  'Крем-суп из брокколи с сыром': '/images/meals/creamy-broccoli-cheese-soup.jpg',
  'Суп с фрикадельками из индейки': '/images/meals/turkey-meatball-soup.jpg',
  'Грибной крем-суп': '/images/meals/creamy-mushroom-soup.jpg',
  'Куриный бульон с овощами': '/images/meals/chicken-broth-vegetables.jpg',
  'Суп с цветной капустой и беконом': '/images/meals/cauliflower-bacon-soup.jpg',
  'Крем-суп из шпината': '/images/meals/creamy-spinach-soup.jpg',
  'Суп с креветками и кокосовым молоком': '/images/meals/shrimp-coconut-soup.jpg',
  'Суп с говядиной и овощами': '/images/meals/beef-vegetable-soup.jpg',
  'Крем-суп из моркови': '/images/meals/creamy-carrot-soup.jpg',
  'Суп-пюре из цукини': '/images/meals/zucchini-puree-soup.jpg',
  'Бульон с яйцом и зеленью': '/images/meals/broth-egg-herbs.jpg',
  'Суп с фрикадельками из говядины': '/images/meals/beef-meatball-soup.jpg',
  'Холодник кето-версия': '/images/meals/keto-okroshka.jpg',
  'Суп с рыбными фрикадельками': '/images/meals/fish-meatball-soup.jpg',
  'Суп-пюре из тыквы и кабачков': '/images/meals/pumpkin-zucchini-soup.jpg',
  'Суп с бараниной и овощами': '/images/meals/lamb-vegetable-soup.jpg',
  'Крем-суп из тыквы': '/images/meals/creamy-pumpkin-soup.jpg',
  'Суп с курицей и лапшой ширатаки': '/images/meals/chicken-shirataki-soup.jpg',
  'Борщ кето-версия': '/images/meals/keto-borscht.jpg',
  'Солянка с мясом': '/images/meals/solyanka-meat.jpg',
  'Харчо по-грузински': '/images/meals/georgian-kharcho.jpg',
  'Том ям с креветками': '/images/meals/tom-yum-shrimp.jpg',
  'Суп с индейкой и овощами': '/images/meals/turkey-vegetable-soup.jpg',
  'Суп-пюре из цветной капусты': '/images/meals/cauliflower-puree-soup.jpg',
  'Крем-суп из авокадо': '/images/meals/creamy-avocado-soup.jpg',
  
  // ГОРЯЧИЕ ВТОРЫЕ (25)
  'Лосось в су-виде с овощами': '/images/meals/sous-vide-salmon-vegetables.jpg',
  'Куриная грудка на гриле с овощами': '/images/meals/grilled-chicken-breast-vegetables.jpg',
  'Говядина, запеченная в духовке': '/images/meals/oven-baked-beef.jpg',
  'Креветки, жаренные на сковороде с чесноком': '/images/meals/pan-fried-shrimp-garlic.jpg',
  'Стейк из говядины на гриле': '/images/meals/grilled-beef-steak.jpg',
  'Куриные крылышки, запеченные в духовке': '/images/meals/oven-baked-chicken-wings.jpg',
  'Лосось, запеченный в фольге': '/images/meals/foil-baked-salmon.jpg',
  'Говядина, тушенная с овощами': '/images/meals/braised-beef-vegetables.jpg',
  'Куриные бедра на гриле': '/images/meals/grilled-chicken-thighs.jpg',
  'Индейка, запеченная с травами': '/images/meals/herb-roasted-turkey.jpg',
  'Кальмары, жаренные в кляре': '/images/meals/fried-squid-rings.jpg',
  'Говядина, жаренная на сковороде': '/images/meals/pan-seared-beef.jpg',
  'Курица в сливочном соусе': '/images/meals/chicken-creamy-sauce.jpg',
  'Лосось на гриле с овощами': '/images/meals/grilled-salmon-vegetables.jpg',
  'Баранина, запеченная с розмарином': '/images/meals/rosemary-roasted-lamb.jpg',
  'Куриная грудка в су-виде': '/images/meals/sous-vide-chicken-breast.jpg',
  'Говяжьи ребрышки на гриле': '/images/meals/grilled-beef-ribs.jpg',
  'Индейка, тушенная с овощами': '/images/meals/braised-turkey-vegetables.jpg',
  'Лосось в аэрогриле': '/images/meals/air-fried-salmon.jpg',
  'Куриная грудка на пару с овощами': '/images/meals/steamed-chicken-breast-vegetables.jpg',
  'Куриные грудки, жаренные на сковороде': '/images/meals/pan-fried-chicken-breasts.jpg',
  'Говядина, запеченная с сыром': '/images/meals/cheese-topped-baked-beef.jpg',
  'Куриные бедра, тушенные с овощами': '/images/meals/braised-chicken-thighs-vegetables.jpg',
  'Лосось, жаренный на гриле': '/images/meals/grilled-salmon-fillet.jpg',
  'Говядина в аэрогриле': '/images/meals/air-fried-beef.jpg',
  
  // КОНДИТЕРСКИЕ (25)
  'Кето-чизкейк без выпечки': '/images/meals/keto-no-bake-cheesecake.jpg',
  'Кексы с шоколадом на миндальной муке': '/images/meals/chocolate-almond-cupcakes.jpg',
  'Мороженое из авокадо и кокоса': '/images/meals/avocado-coconut-ice-cream.jpg',
  'Печенье из миндальной муки': '/images/meals/almond-flour-cookies.jpg',
  'Шоколадный мусс из авокадо': '/images/meals/chocolate-avocado-mousse.jpg',
  'Кето-торт с кремом': '/images/meals/keto-cream-cake.jpg',
  'Тарталетки с ягодами': '/images/meals/berry-tartlets.jpg',
  'Шоколадные конфеты без сахара': '/images/meals/sugar-free-chocolate-truffles.jpg',
  'Пудинг из чиа с ягодами': '/images/meals/chia-pudding-berries.jpg',
  'Кето-круассаны': '/images/meals/keto-croissants.jpg',
  'Пирог с ягодами на миндальной муке': '/images/meals/almond-berry-pie.jpg',
  'Шоколадные брауни кето': '/images/meals/keto-chocolate-brownies.jpg',
  'Мороженое из кокосового молока': '/images/meals/coconut-milk-ice-cream.jpg',
  'Печенье с орехами': '/images/meals/nut-cookies.jpg',
  'Крем-брюле кето-версия': '/images/meals/keto-creme-brulee.jpg',
  'Торт с кремом и ягодами': '/images/meals/cream-cake-berries.jpg',
  'Пирожные с кремом': '/images/meals/keto-cream-puffs.jpg',
  'Шоколадный торт без муки': '/images/meals/flourless-chocolate-cake.jpg',
  'Тарт с лимоном': '/images/meals/keto-lemon-tart.jpg',
  'Печенье с шоколадом': '/images/meals/keto-chocolate-cookies.jpg',
  'Мусс из ягод': '/images/meals/berry-mousse.jpg',
  'Торт с орехами': '/images/meals/keto-nut-cake.jpg',
  'Печенье с кокосом': '/images/meals/coconut-cookies.jpg',
  'Шоколадный фондан': '/images/meals/keto-chocolate-fondant.jpg',
  'Тарталетки с кремом': '/images/meals/cream-tartlets.jpg',
  
  // С СЫРОМ ФЕТА (20)
  'Салат с сыром фета и огурцами': '/images/meals/feta-cucumber-salad.jpg',
  'Запеченная куриная грудка с сыром фета': '/images/meals/baked-chicken-feta.jpg',
  'Омлет с сыром фета и шпинатом': '/images/meals/omelet-feta-spinach.jpg',
  'Салат с сыром фета, авокадо и яйцами': '/images/meals/feta-avocado-egg-salad.jpg',
  'Запеченные кабачки с сыром фета': '/images/meals/baked-zucchini-feta.jpg',
  'Салат с сыром фета и грецкими орехами': '/images/meals/feta-walnut-salad.jpg',
  'Фаршированные перцы с сыром фета': '/images/meals/stuffed-peppers-feta.jpg',
  'Салат с сыром фета и тунцом': '/images/meals/feta-tuna-salad.jpg',
  'Запеченная рыба с сыром фета': '/images/meals/baked-fish-feta.jpg',
  'Салат с сыром фета и брокколи': '/images/meals/feta-broccoli-salad.jpg',
  'Салат с курицей и сыром фета': '/images/meals/chicken-feta-salad.jpg',
  'Яичница с сыром фета и помидорами': '/images/meals/scrambled-eggs-feta-tomatoes.jpg',
  'Салат с сыром фета, оливками и рукколой': '/images/meals/feta-olive-arugula-salad.jpg',
  'Запеченная куриная грудка с сыром фета и шпинатом': '/images/meals/baked-chicken-feta-spinach.jpg',
  'Салат с сыром фета, авокадо и креветками': '/images/meals/feta-avocado-shrimp-salad.jpg',
  'Омлет с сыром фета и помидорами': '/images/meals/omelet-feta-tomatoes.jpg',
  'Салат с сыром фета и свеклой': '/images/meals/feta-beet-salad.jpg',
  'Запеченные баклажаны с сыром фета': '/images/meals/baked-eggplant-feta.jpg',
  'Салат с сыром фета и грушей': '/images/meals/feta-pear-salad.jpg',
  'Сыр фета на гриле с овощами': '/images/meals/grilled-feta-vegetables.jpg',
}

// Функция для получения пути к изображению по названию блюда
export function getMealImage(mealName: string): string | undefined {
  return mealImageMapping[mealName]
}

// Функция для добавления изображений ко всем блюдам
export function addImagesToMeals<T extends { name: string; image?: string }>(meals: T[]): T[] {
  return meals.map(meal => ({
    ...meal,
    image: meal.image || getMealImage(meal.name)
  }))
}

