// Маппинг названий блюд к файлам изображений из personal-chef-meals-kandinsky-prompts.md
// Формат: название блюда -> путь к изображению
export const mealImageMapping: Record<string, string> = {
  // ХОЛОДНЫЕ БЛЮДА (25)
  'Татар из сёмги с авокадо': '/img/recipes/tartar-syomga-avokado.jpg',
  'Салат Цезарь с курицей и пармезаном': '/img/recipes/caesar-salad-chicken-parmesan.jpg',
  'Греческий салат с фетой': '/img/recipes/greek-salad-feta.jpg',
  'Тартар из говядины с яичным желтком': '/img/recipes/beef-tartar-egg-yolk.jpg',
  'Салат с тунцом и авокадо': '/img/recipes/tuna-avocado-salad.jpg',
  'Карпаччо из телятины': '/img/recipes/veal-carpaccio.jpg',
  'Салат из морепродуктов': '/img/recipes/seafood-salad.jpg',
  'Салат с креветками и авокадо': '/img/recipes/shrimp-avocado-salad.jpg',
  'Оливье кето-версия': '/img/recipes/keto-olivier.jpg',
  'Салат с курицей и орехами': '/img/recipes/chicken-nut-salad.jpg',
  'Тартар из лосося с огурцом': '/img/recipes/salmon-tartar-cucumber.jpg',
  'Салат с индейкой и сыром': '/img/recipes/turkey-cheese-salad.jpg',
  'Цезарь с лососем': '/img/recipes/caesar-salmon.jpg',
  'Салат с яйцами и беконом': '/img/recipes/egg-bacon-salad.jpg',
  'Гуакамоле с овощами': '/img/recipes/guacamole-vegetables.jpg',
  'Салат с кальмарами': '/img/recipes/squid-salad.jpg',
  'Салат с мидиями': '/img/recipes/mussel-salad.jpg',
  'Салат с крабом и авокадо': '/img/recipes/crab-avocado-salad.jpg',
  'Салат с печенью и овощами': '/img/recipes/liver-vegetable-salad.jpg',
  'Салат с баклажанами и сыром': '/img/recipes/eggplant-cheese-salad.jpg',
  'Салат с копченой курицей': '/img/recipes/smoked-chicken-salad.jpg',
  'Салат с говядиной и рукколой': '/img/recipes/beef-arugula-salad.jpg',
  'Салат с яйцами пашот': '/img/recipes/poached-egg-salad.jpg',
  'Салат с грибами и сыром': '/img/recipes/mushroom-cheese-salad.jpg',
  'Винегрет с селедкой': '/img/recipes/herring-vinaigrette.jpg',
  
  // ГОРЯЧИЕ ПЕРВЫЕ (25)
  'Крем-суп из брокколи с сыром': '/img/recipes/creamy-broccoli-cheese-soup.jpg',
  'Суп с фрикадельками из индейки': '/img/recipes/turkey-meatball-soup.jpg',
  'Грибной крем-суп': '/img/recipes/creamy-mushroom-soup.jpg',
  'Куриный бульон с овощами': '/img/recipes/chicken-broth-vegetables.jpg',
  'Суп с цветной капустой и беконом': '/img/recipes/cauliflower-bacon-soup.jpg',
  'Крем-суп из шпината': '/img/recipes/creamy-spinach-soup.jpg',
  'Суп с креветками и кокосовым молоком': '/img/recipes/shrimp-coconut-soup.jpg',
  'Суп с говядиной и овощами': '/img/recipes/beef-vegetable-soup.jpg',
  'Крем-суп из моркови': '/img/recipes/creamy-carrot-soup.jpg',
  'Суп-пюре из цукини': '/img/recipes/zucchini-puree-soup.jpg',
  'Бульон с яйцом и зеленью': '/img/recipes/broth-egg-herbs.jpg',
  'Суп с фрикадельками из говядины': '/img/recipes/beef-meatball-soup.jpg',
  'Холодник кето-версия': '/img/recipes/keto-okroshka.jpg',
  'Суп с рыбными фрикадельками': '/img/recipes/fish-meatball-soup.jpg',
  'Суп-пюре из тыквы и кабачков': '/img/recipes/pumpkin-zucchini-soup.jpg',
  'Суп с бараниной и овощами': '/img/recipes/lamb-vegetable-soup.jpg',
  'Крем-суп из тыквы': '/img/recipes/creamy-pumpkin-soup.jpg',
  'Суп с курицей и лапшой ширатаки': '/img/recipes/chicken-shirataki-soup.jpg',
  'Борщ кето-версия': '/img/recipes/keto-borscht.jpg',
  'Солянка с мясом': '/img/recipes/solyanka-meat.jpg',
  'Харчо по-грузински': '/img/recipes/georgian-kharcho.jpg',
  'Том ям с креветками': '/img/recipes/tom-yum-shrimp.jpg',
  'Суп с индейкой и овощами': '/img/recipes/turkey-vegetable-soup.jpg',
  'Суп-пюре из цветной капусты': '/img/recipes/cauliflower-puree-soup.jpg',
  'Крем-суп из авокадо': '/img/recipes/creamy-avocado-soup.jpg',
  
  // ГОРЯЧИЕ ВТОРЫЕ (25)
  'Лосось в су-виде с овощами': '/img/recipes/sous-vide-salmon-vegetables.jpg',
  'Куриная грудка на гриле с овощами': '/img/recipes/grilled-chicken-breast-vegetables.jpg',
  'Говядина, запеченная в духовке': '/img/recipes/oven-baked-beef.jpg',
  'Креветки, жаренные на сковороде с чесноком': '/img/recipes/pan-fried-shrimp-garlic.jpg',
  'Стейк из говядины на гриле': '/img/recipes/grilled-beef-steak.jpg',
  'Куриные крылышки, запеченные в духовке': '/img/recipes/oven-baked-chicken-wings.jpg',
  'Лосось, запеченный в фольге': '/img/recipes/foil-baked-salmon.jpg',
  'Говядина, тушенная с овощами': '/img/recipes/braised-beef-vegetables.jpg',
  'Куриные бедра на гриле': '/img/recipes/grilled-chicken-thighs.jpg',
  'Индейка, запеченная с травами': '/img/recipes/herb-roasted-turkey.jpg',
  'Кальмары на гриле с лимоном': '/img/recipes/grilled-squid-lemon.jpg',
  'Говядина, жаренная на сковороде': '/img/recipes/pan-seared-beef.jpg',
  'Курица в сливочном соусе': '/img/recipes/chicken-creamy-sauce.jpg',
  'Лосось на гриле с овощами': '/img/recipes/grilled-salmon-vegetables.jpg',
  'Баранина, запеченная с розмарином': '/img/recipes/rosemary-roasted-lamb.jpg',
  'Куриная грудка в су-виде': '/img/recipes/sous-vide-chicken-breast.jpg',
  'Говяжьи ребрышки на гриле': '/img/recipes/grilled-beef-ribs.jpg',
  'Индейка, тушенная с овощами': '/img/recipes/braised-turkey-vegetables.jpg',
  'Лосось в аэрогриле': '/img/recipes/air-fried-salmon.jpg',
  'Куриная грудка на пару с овощами': '/img/recipes/steamed-chicken-breast-vegetables.jpg',
  'Куриные грудки, жаренные на сковороде': '/img/recipes/pan-fried-chicken-breasts.jpg',
  'Говядина, запеченная с сыром': '/img/recipes/cheese-topped-baked-beef.jpg',
  'Куриные бедра, тушенные с овощами': '/img/recipes/braised-chicken-thighs-vegetables.jpg',
  'Лосось, жаренный на гриле': '/img/recipes/grilled-salmon-fillet.jpg',
  'Говядина в аэрогриле': '/img/recipes/air-fried-beef.jpg',
  
  // КОНДИТЕРСКИЕ (25)
  'Кето-чизкейк без выпечки': '/img/recipes/keto-no-bake-cheesecake.jpg',
  'Кексы с шоколадом на миндальной муке': '/img/recipes/chocolate-almond-cupcakes.jpg',
  'Мороженое из авокадо и кокоса': '/img/recipes/avocado-coconut-ice-cream.jpg',
  'Печенье из миндальной муки': '/img/recipes/almond-flour-cookies.jpg',
  'Шоколадный мусс из авокадо': '/img/recipes/chocolate-avocado-mousse.jpg',
  'Кето-торт с кремом': '/img/recipes/keto-cream-cake.jpg',
  'Тарталетки с ягодами': '/img/recipes/berry-tartlets.jpg',
  'Шоколадные конфеты без сахара': '/img/recipes/sugar-free-chocolate-truffles.jpg',
  'Пудинг из чиа с ягодами': '/img/recipes/chia-pudding-berries.jpg',
  'Кето-круассаны': '/img/recipes/keto-croissants.jpg',
  'Пирог с ягодами на миндальной муке': '/img/recipes/almond-berry-pie.jpg',
  'Шоколадные брауни кето': '/img/recipes/keto-chocolate-brownies.jpg',
  'Мороженое из кокосового молока': '/img/recipes/coconut-milk-ice-cream.jpg',
  'Печенье с орехами': '/img/recipes/nut-cookies.jpg',
  'Крем-брюле кето-версия': '/img/recipes/keto-creme-brulee.jpg',
  'Торт с кремом и ягодами': '/img/recipes/cream-cake-berries.jpg',
  'Пирожные с кремом': '/img/recipes/keto-cream-puffs.jpg',
  'Шоколадный торт без муки': '/img/recipes/flourless-chocolate-cake.jpg',
  'Тарт с лимоном': '/img/recipes/keto-lemon-tart.jpg',
  'Печенье с шоколадом': '/img/recipes/keto-chocolate-cookies.jpg',
  'Мусс из ягод': '/img/recipes/berry-mousse.jpg',
  'Торт с орехами': '/img/recipes/keto-nut-cake.jpg',
  'Печенье с кокосом': '/img/recipes/coconut-cookies.jpg',
  'Шоколадный фондан': '/img/recipes/keto-chocolate-fondant.jpg',
  'Тарталетки с кремом': '/img/recipes/cream-tartlets.jpg',
  
  // С СЫРОМ ФЕТА (20)
  'Салат с сыром фета и огурцами': '/img/recipes/feta-cucumber-salad.jpg',
  'Запеченная куриная грудка с сыром фета': '/img/recipes/baked-chicken-feta.jpg',
  'Омлет с сыром фета и шпинатом': '/img/recipes/omelet-feta-spinach.jpg',
  'Салат с сыром фета, авокадо и яйцами': '/img/recipes/feta-avocado-egg-salad.jpg',
  'Запеченные кабачки с сыром фета': '/img/recipes/baked-zucchini-feta.jpg',
  'Салат с сыром фета и грецкими орехами': '/img/recipes/feta-walnut-salad.jpg',
  'Фаршированные перцы с сыром фета': '/img/recipes/stuffed-peppers-feta.jpg',
  'Салат с сыром фета и тунцом': '/img/recipes/feta-tuna-salad.jpg',
  'Запеченная рыба с сыром фета': '/img/recipes/baked-fish-feta.jpg',
  'Салат с сыром фета и брокколи': '/img/recipes/feta-broccoli-salad.jpg',
  'Салат с курицей и сыром фета': '/img/recipes/chicken-feta-salad.jpg',
  'Яичница с сыром фета и помидорами': '/img/recipes/scrambled-eggs-feta-tomatoes.jpg',
  'Салат с сыром фета, оливками и рукколой': '/img/recipes/feta-olive-arugula-salad.jpg',
  'Запеченная куриная грудка с сыром фета и шпинатом': '/img/recipes/baked-chicken-feta-spinach.jpg',
  'Салат с сыром фета, авокадо и креветками': '/img/recipes/feta-avocado-shrimp-salad.jpg',
  'Омлет с сыром фета и помидорами': '/img/recipes/omelet-feta-tomatoes.jpg',
  'Салат с сыром фета и свеклой': '/img/recipes/feta-beet-salad.jpg',
  'Запеченные баклажаны с сыром фета': '/img/recipes/baked-eggplant-feta.jpg',
  'Салат с сыром фета и грушей': '/img/recipes/feta-pear-salad.jpg',
  'Сыр фета на гриле с овощами': '/img/recipes/grilled-feta-vegetables.jpg',
  
  // БЛЮДА СУ-ВИД (дополнительные)
  'Говядина в су-виде с овощами': '/img/recipes/sous-vide-beef-vegetables.jpg',
  'Стейк из говядины в су-виде': '/img/recipes/sous-vide-beef-steak.jpg',
  'Индейка в су-виде с овощами': '/img/recipes/sous-vide-turkey-vegetables.jpg',
  'Сёмга в су-виде с овощами': '/img/recipes/sous-vide-salmon-vegetables.jpg',
  'Куриные бедра в су-виде': '/img/recipes/sous-vide-chicken-thighs.jpg',
  'Свинина в су-виде с овощами': '/img/recipes/sous-vide-pork-vegetables.jpg',
  'Баранина в су-виде с овощами': '/img/recipes/sous-vide-lamb-vegetables.jpg',
  'Куриная грудка в су-виде с брокколи': '/img/recipes/sous-vide-chicken-breast-broccoli.jpg',
  'Свиная вырезка в су-виде с кабачками': '/img/recipes/sous-vide-pork-tenderloin-zucchini.jpg',
  'Тунец в су-виде с авокадо': '/img/recipes/sous-vide-tuna-avocado.jpg',
  'Ягненок в су-виде с розмарином': '/img/recipes/sous-vide-lamb-rosemary.jpg',
  'Утка в су-виде с овощами': '/img/recipes/sous-vide-duck-vegetables.jpg',
  
  // БЛЮДА АЭРОГРИЛЬ (дополнительные)
  'Куриные крылышки в аэрогриле': '/img/recipes/air-fry-chicken-wings.jpg',
  'Лосось в аэрогриле с овощами': '/img/recipes/air-fry-salmon-vegetables.jpg',
  'Говядина в аэрогриле с брокколи': '/img/recipes/air-fry-beef-broccoli.jpg',
  'Куриные бедра в аэрогриле': '/img/recipes/air-fry-chicken-thighs.jpg',
  'Креветки в аэрогриле с овощами': '/img/recipes/air-fry-shrimp-vegetables.jpg',
  'Свинина в аэрогриле с кабачками': '/img/recipes/air-fry-pork-zucchini.jpg',
  'Индейка в аэрогриле с овощами': '/img/recipes/air-fry-turkey-vegetables.jpg',
  'Рыбные стейки в аэрогриле': '/img/recipes/air-fry-fish-steaks.jpg',
  
  // ДОПОЛНИТЕЛЬНЫЕ МАППИНГИ (добавлены для генератора "Личный шеф")
  // Рецепты из enhancedMealsData.ts без фото
  
  // Супы
  'Суп-пюре из кабачков': '/img/recipes/zucchini-puree-soup.jpg',
  'Суп с рыбой и овощами': '/img/recipes/fish-soup-vegetables.jpg',
  'Суп с грибами и сливками': '/img/recipes/creamy-mushroom-soup.jpg',
  'Суп с курицей и шпинатом': '/img/recipes/chicken-spinach-soup.jpg',
  'Суп с лососем и овощами': '/img/recipes/salmon-vegetable-soup.jpg',
  'Суп с индейкой и кабачками': '/img/recipes/turkey-zucchini-soup.jpg',
  'Суп с бараниной и баклажанами': '/img/recipes/lamb-vegetable-soup.jpg',
  'Суп с курицей и брокколи': '/img/recipes/chicken-broccoli-soup.jpg',
  
  // Горячие блюда
  'Говядина, тушеная с овощами': '/img/recipes/braised-beef-vegetables.jpg',
  'Куриная грудка с горчичным соусом': '/img/recipes/chicken-creamy-sauce.jpg',
  'Стейк с горчицей и травами': '/img/recipes/grilled-beef-steak.jpg',
  'Рыба с хреном и сметаной': '/img/recipes/baked-fish-vegetables.jpg',
  'Говядина с хреном': '/img/recipes/oven-baked-beef.jpg',
  'Куриные крылышки с горчицей и медом': '/img/recipes/spicy-chicken-wings.jpg',
  'Куриная грудка в сливочном соусе с грибами': '/img/recipes/chicken-mushrooms-cream.jpg',
  'Говядина в красном вине': '/img/recipes/beef-stew-vegetables.jpg',
  'Рыба в томатном соусе': '/img/recipes/fish-tomato-sauce.jpg',
  'Куриные бедра в медовом соусе': '/img/recipes/braised-chicken-thighs-vegetables.jpg',
  'Говядина с овощами в горшочке': '/img/recipes/beef-goulash-vegetables.jpg',
  'Куриная грудка с овощами в горшочке': '/img/recipes/chicken-vegetables-pot.jpg',
  'Говядина с грибами в сливочном соусе': '/img/recipes/beef-mushrooms-cream.jpg',
  'Рыба с овощами в фольге': '/img/recipes/fish-vegetables-foil.jpg',
  'Куриные бедра с овощами в духовке': '/img/recipes/chicken-thighs-vegetables-oven.jpg',
  'Говядина с овощами на пару': '/img/recipes/steamed-fish-vegetables.jpg',
  
  // Салаты
  'Салат с горчичной заправкой': '/img/recipes/greek-salad-feta.jpg',
  'Салат с хреном и яйцами': '/img/recipes/egg-salad-avocado.jpg',
  'Винегрет кето-версия': '/img/recipes/herring-vinaigrette.jpg',
  'Салат с курицей и ананасом': '/img/recipes/chicken-nut-salad.jpg',
  'Салат с тунцом и фасолью': '/img/recipes/tuna-avocado-salad.jpg',
  'Салат с креветками и манго': '/img/recipes/shrimp-avocado-salad.jpg',
  'Салат с курицей и гранатом': '/img/recipes/chicken-pecan-salad.jpg',
  'Салат с курицей и яблоками': '/img/recipes/chicken-avocado-salad.jpg',
  'Салат с тунцом и яйцами': '/img/recipes/tuna-egg-salad.jpg',
  'Салат с курицей и виноградом': '/img/recipes/chicken-grape-salad.jpg',
  'Салат с лососем и спаржей': '/img/recipes/salmon-broccoli.jpg',
  'Салат с курицей и апельсином': '/img/recipes/chicken-orange-salad.jpg',
  'Салат с лососем и авокадо': '/img/recipes/salmon-avocado-salad.jpg',
  'Салат с индейкой и авокадо': '/img/recipes/turkey-avocado-salad.jpg',
  'Салат с креветками и огурцом': '/img/recipes/shrimp-cucumber-salad.jpg',
  'Салат с курицей и киноа': '/img/recipes/chicken-quinoa-salad.jpg',
  
  // Десерты
  'Кето-панкейки': '/img/recipes/keto-pancakes-berries.jpg',
  'Кето-вафли': '/img/recipes/bacon-waffles.jpg',
  'Кето-кексы с ягодами': '/img/recipes/keto-blueberry-muffins.jpg',
  'Кето-пончики': '/img/recipes/keto-donuts.jpg',
  'Кето-тирамису': '/img/recipes/keto-tiramisu.jpg',
  'Кето-мороженое из авокадо': '/img/recipes/keto-avocado-ice-cream.jpg',
  'Кето-печенье с орехами': '/img/recipes/keto-nut-cookies.jpg',
  'Кето-кексы с лимоном': '/img/recipes/keto-lemon-cupcakes.jpg',
  'Кето-чизкейк с ягодами': '/img/recipes/keto-cheesecake.jpg',
  'Кето-шоколадный мусс': '/img/recipes/keto-chocolate-mousse.jpg',
  
  // ДОПОЛНИТЕЛЬНЫЕ МАППИНГИ для additionalMealsPart6-11
  
  // additionalMealsPart6
  'Салат с авокадо и креветками': '/img/recipes/shrimp-avocado-salad.jpg',
  'Тартар из говядины с каперсами': '/img/recipes/beef-tartar-egg-yolk.jpg',
  'Суп с лососем и сливками': '/img/recipes/salmon-vegetable-soup.jpg',
  'Холодный суп гаспачо': '/img/recipes/keto-okroshka.jpg',
  'Свинина в сливочно-грибном соусе': '/img/recipes/beef-mushrooms-cream.jpg',
  'Куриные ножки в медово-горчичном маринаде': '/img/recipes/spicy-chicken-wings.jpg',
  'Кето-панна-котта с ягодами': '/img/recipes/keto-panna-cotta.jpg',
  'Кето-брауни с орехами': '/img/recipes/keto-nut-brownies.jpg',
  
  // additionalMealsPart7
  'Салат с копченой рыбой и яйцами': '/img/recipes/smoked-chicken-salad.jpg',
  'Карпаччо из лосося': '/img/recipes/veal-carpaccio.jpg',
  'Салат с печенью и яблоками': '/img/recipes/liver-vegetable-salad.jpg',
  'Суп с курицей и кокосовым молоком': '/img/recipes/chicken-coconut-sauce.jpg',
  'Крем-суп из цветной капусты и брокколи': '/img/recipes/cauliflower-puree-soup.jpg',
  'Суп с мидиями и белым вином': '/img/recipes/mussel-salad.jpg',
  'Индейка в сливочном соусе с грибами': '/img/recipes/turkey-broccoli-cheese.jpg',
  'Баранина на косточке с овощами': '/img/recipes/rosemary-roasted-lamb.jpg',
  'Креветки в чесночно-сливочном соусе': '/img/recipes/shrimp-garlic-butter.jpg',
  'Курица в терияки-соусе': '/img/recipes/salmon-keto-teriyaki.jpg',
  'Стейк из тунца с авокадо': '/img/recipes/sous-vide-tuna-avocado.jpg',
  'Куриные бедра в медово-соевом маринаде': '/img/recipes/grilled-chicken-thighs.jpg',
  'Кето-маффины с черникой': '/img/recipes/keto-blueberry-muffins.jpg',
  
  // additionalMealsPart8
  'Салат с морепродуктами и авокадо': '/img/recipes/seafood-salad.jpg',
  'Тартар из тунца с авокадо': '/img/recipes/tuna-avocado-salad.jpg',
  'Салат с козьим сыром и грушей': '/img/recipes/feta-walnut-salad.jpg',
  'Салат с яйцами пашот и шпинатом': '/img/recipes/poached-egg-salad.jpg',
  'Суп с индейкой и лапшой ширатаки': '/img/recipes/chicken-shirataki-soup.jpg',
  'Суп с фрикадельками из курицы': '/img/recipes/turkey-meatball-soup.jpg',
  'Крем-суп из тыквы с имбирем': '/img/recipes/creamy-pumpkin-soup.jpg',
  'Лосось в соусе терияки': '/img/recipes/salmon-keto-teriyaki.jpg',
  'Куриные крылышки в медово-горчичном соусе': '/img/recipes/oven-baked-chicken-wings.jpg',
  'Индейка в соусе из клюквы': '/img/recipes/herb-roasted-turkey.jpg',
  'Креветки в кокосовой панировке': '/img/recipes/pan-fried-shrimp-garlic.jpg',
  'Баранина в йогуртовом маринаде': '/img/recipes/sous-vide-lamb-rosemary.jpg',
  'Кето-вафли с ягодами': '/img/recipes/bacon-waffles.jpg',
  'Кето-пончики с глазурью': '/img/recipes/keto-donuts.jpg',
  
  // additionalMealsPart9
  'Салат с рукколой и пармезаном': '/img/recipes/beef-arugula-salad.jpg',
  'Салат Цезарь с курицей': '/img/recipes/caesar-salad-chicken-parmesan.jpg',
  'Салат с моцареллой и помидорами': '/img/recipes/greek-salad-feta.jpg',
  'Салат с сельдереем и яблоками': '/img/recipes/chicken-avocado-salad.jpg',
  'Салат с копченым лососем': '/img/recipes/salmon-avocado-salad.jpg',
  'Салат с курицей и авокадо': '/img/recipes/chicken-avocado-salad.jpg',
  'Суп с лапшой и курицей': '/img/recipes/chicken-shirataki-soup.jpg',
  'Крем-суп из спаржи': '/img/recipes/creamy-broccoli-soup.jpg',
  'Суп с мидиями и томатами': '/img/recipes/tom-yum-shrimp.jpg',
  'Суп с курицей и яйцом': '/img/recipes/broth-egg-herbs.jpg',
  'Крем-суп из грибов': '/img/recipes/creamy-mushroom-soup.jpg',
  'Стейк из лосося с соусом песто': '/img/recipes/grilled-salmon-fillet.jpg',
  'Куриные грудки в панировке из миндаля': '/img/recipes/chicken-parmesan.jpg',
  'Говядина в горчичном соусе': '/img/recipes/beef-steak-green-salad.jpg',
  'Индейка с яблоками': '/img/recipes/herb-roasted-turkey.jpg',
  'Креветки в томатном соусе': '/img/recipes/shrimp-garlic-sauce.jpg',
  'Курица с грибами и сливками': '/img/recipes/chicken-mushrooms-cream.jpg',
  'Лосось в медово-соевом соусе': '/img/recipes/salmon-keto-teriyaki.jpg',
  'Баранина с розмарином': '/img/recipes/rosemary-roasted-lamb.jpg',
  'Куриные крылышки в остро-сладком соусе': '/img/recipes/keto-chicken-wings.jpg',
  'Говядина с брокколи': '/img/recipes/beef-broccoli-sauce.jpg',
  'Кето-печенье с шоколадом': '/img/recipes/keto-chocolate-muffins.jpg',
  'Кето-пудинг из чиа': '/img/recipes/keto-chia-pudding.jpg',
  'Кето-торт с кокосом': '/img/recipes/keto-cream-cake.jpg',
  'Кето-мороженое из кокоса': '/img/recipes/coconut-milk-ice-cream.jpg',
  
  // additionalMealsPart10
  'Салат с тунцом и огурцами': '/img/recipes/tuna-avocado-salad.jpg',
  'Салат с моцареллой и персиками': '/img/recipes/feta-walnut-salad.jpg',
  'Салат с крабовым мясом': '/img/recipes/crab-avocado-salad.jpg',
  'Суп с курицей и лапшой': '/img/recipes/chicken-shirataki-soup.jpg',
  'Крем-суп из кабачков': '/img/recipes/zucchini-puree-soup.jpg',
  'Холодный суп из огурцов': '/img/recipes/keto-okroshka.jpg',
  'Суп с индейкой и рисом': '/img/recipes/turkey-vegetable-soup.jpg',
  'Крем-суп из цветной капусты': '/img/recipes/cauliflower-puree-soup.jpg',
  'Суп с говядиной и лапшой': '/img/recipes/beef-vegetable-soup.jpg',
  'Курица в апельсиновом соусе': '/img/recipes/chicken-creamy-sauce.jpg',
  'Лосось в соусе из горчицы': '/img/recipes/baked-salmon-lemon-herbs.jpg',
  'Индейка с овощами': '/img/recipes/turkey-steamed-vegetables.jpg',
  'Креветки в кокосовом соусе': '/img/recipes/shrimp-coconut-soup.jpg',
  'Курица с грибами': '/img/recipes/chicken-mushroom-cream.jpg',
  'Лосось на пару': '/img/recipes/steamed-fish-vegetables.jpg',
  'Говядина с морковью': '/img/recipes/beef-stew-vegetables.jpg',
  'Курица в томатном соусе': '/img/recipes/fish-tomato-sauce.jpg',
  'Кето-творожная запеканка': '/img/recipes/keto-cheesecake.jpg',
  'Кето-сырники': '/img/recipes/keto-cottage-pancakes.jpg',
  'Кето-пудинг с шоколадом': '/img/recipes/keto-avocado-pudding.jpg',
  
  // additionalMealsPart11
  'Салат с курицей и орехами пекан': '/img/recipes/chicken-pecan-salad.jpg',
  'Курица в сливочно-грибном соусе': '/img/recipes/chicken-mushrooms-cream.jpg',
  
  // ============================================
  // KETO RECIPES DATA (из ketoRecipesData.ts)
  // ============================================
  
  // Завтраки
  'Омлет с авокадо и сыром': '/img/recipes/avocado-cheese-omlet.jpg',
  'Яичница с беконом и шпинатом': '/img/recipes/bacon-eggs-spinach.jpg',
  'Чиа-пудинг с кокосовым молоком': '/img/recipes/chia-coconut-pudding.jpg',
  'Яйца Бенедикт на кето-булочке': '/img/recipes/eggs-benedict-keto.jpg',
  'Скрэмбл с лососем и каперсами': '/img/recipes/scrambled-eggs-salmon.jpg',
  'Запеченные яйца в авокадо': '/img/recipes/baked-eggs-avocado.jpg',
  'Кето-гранола с греческим йогуртом': '/img/recipes/keto-granola-yogurt.jpg',
  'Смузи с MCT-маслом и ягодами': '/img/recipes/smoothie-mct-berries.jpg',
  'Творожные кето-оладьи': '/img/recipes/keto-cottage-pancakes.jpg',
  'Бекон-вафли': '/img/recipes/bacon-waffles.jpg',
  'Яйца в облачках с сыром': '/img/recipes/cloud-eggs-cheese.jpg',
  'Кето-хлеб с семенами': '/img/recipes/keto-seed-bread.jpg',
  'Яичный пудинг с беконом': '/img/recipes/egg-pudding-bacon.jpg',
  'Омлет-рулет с начинкой': '/img/recipes/omelette-roll-filling.jpg',
  'Кето-блинчики с ягодами': '/img/recipes/keto-pancakes-berries.jpg',
  'Сырные оладьи с зеленью': '/img/recipes/cheese-pancakes-herbs.jpg',
  'Яичный салат в авокадо': '/img/recipes/egg-salad-avocado.jpg',
  'Кето-каша из семян': '/img/recipes/keto-seed-porridge.jpg',
  'Скрэмбл с грибами и сыром': '/img/recipes/scrambled-mushrooms-cheese.jpg',
  
  // Салаты и закуски
  'Кето Цезарь с курицей': '/img/recipes/keto-caesar-salad.jpg',
  'Тунец в лодочках из салата': '/img/recipes/tuna-lettuce-boats.jpg',
  'Куриная грудка с авокадо и салатом': '/img/recipes/chicken-avocado-salad.jpg',
  'Куриный салат с орехами': '/img/recipes/chicken-nut-salad.jpg',
  'Салат с яйцом и беконом': '/img/recipes/egg-bacon-salad.jpg',
  'Салат Нисуаз кето-версия': '/img/recipes/keto-nicoise.jpg',
  'Огурцы с кремовым сыром': '/img/recipes/cucumber-cream-cheese-rolls.jpg',
  'Фаршированные яйца с авокадо': '/img/recipes/deviled-eggs-avocado.jpg',
  'Сырная тарелка с орехами': '/img/recipes/nuts-cheese-plate.jpg',
  'Орехи макадамия с темным шоколадом': '/img/recipes/macadamia-dark-chocolate.jpg',
  'Сырные чипсы': '/img/recipes/cheese-chips.jpg',
  'Огуречные рулетики с лососем': '/img/recipes/cucumber-salmon-rolls.jpg',
  'Жареные орехи с солью': '/img/recipes/fried-nuts-salt.jpg',
  'Сырный спред с овощами': '/img/recipes/cheese-spread-vegetables.jpg',
  'Авокадо с тунцом': '/img/recipes/avocado-tuna.jpg',
  'Кето-чипсы из капусты': '/img/recipes/keto-kale-chips.jpg',
  'Сырные шарики с орехами': '/img/recipes/cheese-nut-balls.jpg',
  'Овощные палочки с соусом': '/img/recipes/vegetable-sticks-dip.jpg',
  'Сырные палочки': '/img/recipes/cheese-sticks.jpg',
  'Оливки фаршированные': '/img/recipes/stuffed-olives.jpg',
  'Сырные шарики в кокосе': '/img/recipes/cheese-balls-coconut.jpg',
  
  // Супы
  'Крем-суп из брокколи': '/img/recipes/creamy-broccoli-soup.jpg',
  'Кето-суп с курицей и овощами': '/img/recipes/keto-chicken-vegetable-soup.jpg',
  
  // Горячие блюда
  'Рыбные котлеты из тунца': '/img/recipes/tuna-fish-cakes.jpg',
  'Говядина с цветной капустой': '/img/recipes/beef-cauliflower.jpg',
  'Лосось с брокколи': '/img/recipes/salmon-broccoli.jpg',
  'Кето-бургер с салатом': '/img/recipes/keto-burger.jpg',
  'Куриные крылышки в кето-соусе': '/img/recipes/keto-chicken-wings.jpg',
  'Кето-пицца на капустной основе': '/img/recipes/keto-cauliflower-pizza.jpg',
  'Кето-лазанья с кабачками': '/img/recipes/keto-zucchini-lasagna.jpg',
  'Куриная грудка с пармезаном': '/img/recipes/chicken-parmesan.jpg',
  'Говяжий гуляш с овощами': '/img/recipes/beef-goulash-vegetables.jpg',
  'Лосось терияки кето-версия': '/img/recipes/salmon-keto-teriyaki.jpg',
  'Кето-пицца на миндальной основе': '/img/recipes/keto-almond-pizza.jpg',
  'Индейка с овощами на пару': '/img/recipes/turkey-steamed-vegetables.jpg',
  'Говядина с брокколи в соусе': '/img/recipes/beef-broccoli-sauce.jpg',
  'Рыбные котлеты из трески': '/img/recipes/cod-fish-cakes.jpg',
  'Стейк с зелёным салатом': '/img/recipes/beef-steak-green-salad.jpg',
  'Запечённый лосось с лимоном': '/img/recipes/baked-salmon-lemon-herbs.jpg',
  'Курица с грибами в сливках': '/img/recipes/chicken-mushrooms-cream.jpg',
  'Запеченная курица с овощами': '/img/recipes/baked-chicken-vegetables.jpg',
  'Рыба на пару с овощами': '/img/recipes/steamed-fish-vegetables.jpg',
  'Говядина с кабачками': '/img/recipes/beef-zucchini.jpg',
  'Креветки с чесноком и маслом': '/img/recipes/shrimp-garlic-butter.jpg',
  'Лосось с овощами гриль': '/img/recipes/grilled-salmon-vegetables.jpg',
  'Куриные крылышки в специях': '/img/recipes/spicy-chicken-wings.jpg',
  'Рыбный суп с овощами': '/img/recipes/fish-soup-vegetables.jpg',
  'Говяжий стейк с зеленой фасолью': '/img/recipes/beef-steak-green-beans.jpg',
  'Лосось в кокосовом соусе': '/img/recipes/salmon-coconut-sauce.jpg',
  'Кето-паста из цуккини': '/img/recipes/keto-zucchini-pasta.jpg',
  'Индейка с брокколи и сыром': '/img/recipes/turkey-broccoli-cheese.jpg',
  'Кето-чили кон карне': '/img/recipes/keto-chili-con-carne.jpg',
  'Запеченная рыба с овощами': '/img/recipes/baked-fish-vegetables.jpg',
  'Куриные бедра с капустой': '/img/recipes/braised-chicken-thighs-vegetables.jpg',
  'Лосось в фольге с травами': '/img/recipes/salmon-foil-herbs.jpg',
  'Говяжий рагу с овощами': '/img/recipes/beef-stew-vegetables.jpg',
  'Креветки в чесночном соусе': '/img/recipes/shrimp-garlic-sauce.jpg',
  'Индейка с брюссельской капустой': '/img/recipes/turkey-brussels-sprouts.jpg',
  'Рыбное карри кето-версия': '/img/recipes/fish-keto-curry.jpg',
  'Курица в кокосовом соусе': '/img/recipes/chicken-coconut-sauce.jpg',
  'Говяжьи ребра с овощами': '/img/recipes/beef-ribs-vegetables.jpg',
  
  // Перекусы
  'Кето-батончики с орехами': '/img/recipes/keto-nut-bars.jpg',
  'Кето-крекеры из семян': '/img/recipes/keto-seed-crackers.jpg',
  'Кето-дропсы с кокосом': '/img/recipes/keto-coconut-drops.jpg',
  'Кето-печенье с миндалем': '/img/recipes/keto-almond-cookies.jpg',
  'Ореховое масло с овощами': '/img/recipes/nut-butter-vegetables.jpg',
  'Кето-крекеры из пармезана': '/img/recipes/keto-parmesan-crackers.jpg',
  'Беконные чипсы': '/img/recipes/bacon-chips.jpg',
  'Овощные чипсы из кабачков': '/img/recipes/zucchini-chips.jpg',
  'Сырная закуска с орехами': '/img/recipes/cheese-nut-appetizer.jpg',
  'Кето-чипсы из пармезана и миндаля': '/img/recipes/keto-parmesan-almond-chips.jpg',
  
  // Десерты
  'Шоколадный мусс': '/img/recipes/chocolate-avocado-mousse.jpg',
  'Чизкейк в стаканчике': '/img/recipes/berry-cheesecake-cup.jpg',
  'Миндальное печенье': '/img/recipes/almond-keto-cookies.jpg',
  'Кето-мороженое с ванилью': '/img/recipes/keto-vanilla-ice-cream.jpg',
  'Кето-брауни': '/img/recipes/keto-brownies.jpg',
  'Кето-чизкейк': '/img/recipes/keto-cheesecake.jpg',
  'Кето-панна-котта': '/img/recipes/keto-panna-cotta.jpg',
  'Кето-фруктовый салат': '/img/recipes/keto-fruit-salad.jpg',
  'Кето-пудинг из авокадо': '/img/recipes/keto-avocado-pudding.jpg',
  'Кето-кексы с шоколадом': '/img/recipes/keto-chocolate-cupcakes.jpg',
  'Кето-мороженое с клубникой': '/img/recipes/keto-strawberry-ice-cream.jpg',
  'Кето-крем-брюле': '/img/recipes/keto-creme-brulee.jpg',
  'Кето-трюфели': '/img/recipes/keto-truffles.jpg',
  'Кето-маффины с шоколадом': '/img/recipes/keto-chocolate-muffins.jpg',
  'Кето-пирог с лимоном': '/img/recipes/keto-lemon-pie.jpg',
  'Кето-кексы с ванилью': '/img/recipes/keto-vanilla-cupcakes.jpg',
  'Кето-мороженое с орехами': '/img/recipes/keto-nut-ice-cream.jpg',
  
  // ============================================
  // БЛЮДА НА ГРИЛЕ (новые)
  // ============================================
  'Стейк рибай на гриле': '/img/recipes/grilled-ribeye-steak.jpg',
  'Свиные отбивные на гриле': '/img/recipes/grilled-pork-chops.jpg',
  'Бараньи котлеты на гриле': '/img/recipes/grilled-lamb-chops.jpg',
  'Куриные стейки на гриле с травами': '/img/recipes/grilled-chicken-steaks-herbs.jpg',
  'Шашлык из говядины': '/img/recipes/beef-shashlik.jpg',
  'Куриные крылышки на гриле': '/img/recipes/grilled-chicken-wings.jpg',
  'Дорадо на гриле целиком': '/img/recipes/grilled-dorado-whole.jpg',
  'Стейк из тунца на гриле': '/img/recipes/grilled-tuna-steak.jpg',
  'Креветки на гриле с чесноком': '/img/recipes/grilled-shrimp-garlic.jpg',
  'Стейк из лосося на гриле': '/img/recipes/grilled-salmon-steak.jpg',
  'Сибас на гриле с фенхелем': '/img/recipes/grilled-seabass-fennel.jpg',
  'Овощи на гриле ассорти': '/img/recipes/grilled-vegetables-assorted.jpg',
  'Стейк из цветной капусты на гриле': '/img/recipes/grilled-cauliflower-steak.jpg',
  'Телячья печень на сковороде-гриль': '/img/recipes/grilled-veal-liver.jpg',
  'Утиная грудка на гриле': '/img/recipes/grilled-duck-breast.jpg',
  'Индейка-стейк на гриле': '/img/recipes/grilled-turkey-steak.jpg',
  'Кролик на гриле с розмарином': '/img/recipes/grilled-rabbit-rosemary.jpg',
  'Перепелки на гриле': '/img/recipes/grilled-quail.jpg',
  'Говяжьи медальоны на гриле': '/img/recipes/grilled-beef-medallions.jpg',
  'Форель на гриле целиком': '/img/recipes/grilled-trout-whole.jpg',
  
  // ============================================
  // БЛЮДА НА ПАРУ (новые)
  // ============================================
  'Лосось на пару с имбирем': '/img/recipes/steamed-salmon-ginger.jpg',
  'Треска на пару с овощами': '/img/recipes/steamed-cod-vegetables.jpg',
  'Дим-самы с креветками': '/img/recipes/steamed-shrimp-dumplings.jpg',
  'Сибас на пару по-кантонски': '/img/recipes/steamed-seabass-cantonese.jpg',
  'Морской окунь на пару с травами': '/img/recipes/steamed-sea-bass-herbs.jpg',
  'Мидии на пару в белом вине': '/img/recipes/steamed-mussels-wine.jpg',
  'Куриная грудка на пару с лимоном': '/img/recipes/steamed-chicken-breast-lemon.jpg',
  'Индейка на пару с овощами': '/img/recipes/steamed-turkey-vegetables.jpg',
  'Кнели из курицы на пару': '/img/recipes/steamed-chicken-quenelles.jpg',
  'Паровые котлеты из индейки': '/img/recipes/steamed-turkey-cutlets.jpg',
  'Говядина на пару с имбирем': '/img/recipes/steamed-beef-ginger.jpg',
  'Куриные рулетики на пару': '/img/recipes/steamed-chicken-rolls.jpg',
  'Брокколи на пару с чесноком': '/img/recipes/steamed-broccoli-garlic.jpg',
  'Спаржа на пару с голландским соусом': '/img/recipes/steamed-asparagus-hollandaise.jpg',
  'Цветная капуста на пару с сыром': '/img/recipes/steamed-cauliflower-cheese.jpg',
  'Стручковая фасоль на пару': '/img/recipes/steamed-green-beans.jpg',
  'Кабачки на пару с мятой': '/img/recipes/steamed-zucchini-mint.jpg',
  'Яйца на пару по-китайски': '/img/recipes/steamed-eggs-chinese.jpg',
  'Паровой омлет с сыром': '/img/recipes/steamed-omelet-cheese.jpg',
}

// Функция для получения пути к изображению по названию блюда
export function getMealImage(mealName: string): string | undefined {
  return mealImageMapping[mealName]
}

// Функция для добавления изображений ко всем блюдам
export function addImagesToMeals<T extends { name: string; image?: string }>(meals: T[]): T[] {
  return meals.map(meal => ({
    ...meal,
    image: meal.image || getMealImage(meal.name)
  }))
}

