// Маппинг названий блюд к файлам изображений из personal-chef-meals-kandinsky-prompts.md
// Формат: название блюда -> путь к изображению
export const mealImageMapping: Record<string, string> = {
  // ХОЛОДНЫЕ БЛЮДА (25)
  'Татар из сёмги с авокадо': '/img/recipes/tartar-syomga-avokado.jpg',
  'Салат Цезарь с курицей и пармезаном': '/img/recipes/caesar-salad-chicken-parmesan.jpg',
  'Греческий салат с фетой': '/img/recipes/greek-salad-feta.jpg',
  'Тартар из говядины с яичным желтком': '/img/recipes/beef-tartar-egg-yolk.jpg',
  'Салат с тунцом и авокадо': '/img/recipes/tuna-avocado-salad.jpg',
  'Карпаччо из телятины': '/img/recipes/veal-carpaccio.jpg',
  'Салат из морепродуктов': '/img/recipes/seafood-salad.jpg',
  'Салат с креветками и авокадо': '/img/recipes/shrimp-avocado-salad.jpg',
  'Оливье кето-версия': '/img/recipes/keto-olivier.jpg',
  'Салат с курицей и орехами': '/img/recipes/chicken-nut-salad.jpg',
  'Тартар из лосося с огурцом': '/img/recipes/salmon-tartar-cucumber.jpg',
  'Салат с индейкой и сыром': '/img/recipes/turkey-cheese-salad.jpg',
  'Цезарь с лососем': '/img/recipes/caesar-salmon.jpg',
  'Салат с яйцами и беконом': '/img/recipes/egg-bacon-salad.jpg',
  'Гуакамоле с овощами': '/img/recipes/guacamole-vegetables.jpg',
  'Салат с кальмарами': '/img/recipes/squid-salad.jpg',
  'Салат с мидиями': '/img/recipes/mussel-salad.jpg',
  'Салат с крабом и авокадо': '/img/recipes/crab-avocado-salad.jpg',
  'Салат с печенью и овощами': '/img/recipes/liver-vegetable-salad.jpg',
  'Салат с баклажанами и сыром': '/img/recipes/eggplant-cheese-salad.jpg',
  'Салат с копченой курицей': '/img/recipes/smoked-chicken-salad.jpg',
  'Салат с говядиной и рукколой': '/img/recipes/beef-arugula-salad.jpg',
  'Салат с яйцами пашот': '/img/recipes/poached-egg-salad.jpg',
  'Салат с грибами и сыром': '/img/recipes/mushroom-cheese-salad.jpg',
  'Винегрет с селедкой': '/img/recipes/herring-vinaigrette.jpg',
  
  // ГОРЯЧИЕ ПЕРВЫЕ (25)
  'Крем-суп из брокколи с сыром': '/img/recipes/creamy-broccoli-cheese-soup.jpg',
  'Суп с фрикадельками из индейки': '/img/recipes/turkey-meatball-soup.jpg',
  'Грибной крем-суп': '/img/recipes/creamy-mushroom-soup.jpg',
  'Куриный бульон с овощами': '/img/recipes/chicken-broth-vegetables.jpg',
  'Суп с цветной капустой и беконом': '/img/recipes/cauliflower-bacon-soup.jpg',
  'Крем-суп из шпината': '/img/recipes/creamy-spinach-soup.jpg',
  'Суп с креветками и кокосовым молоком': '/img/recipes/shrimp-coconut-soup.jpg',
  'Суп с говядиной и овощами': '/img/recipes/beef-vegetable-soup.jpg',
  'Крем-суп из моркови': '/img/recipes/creamy-carrot-soup.jpg',
  'Суп-пюре из цукини': '/img/recipes/zucchini-puree-soup.jpg',
  'Бульон с яйцом и зеленью': '/img/recipes/broth-egg-herbs.jpg',
  'Суп с фрикадельками из говядины': '/img/recipes/beef-meatball-soup.jpg',
  'Холодник кето-версия': '/img/recipes/keto-okroshka.jpg',
  'Суп с рыбными фрикадельками': '/img/recipes/fish-meatball-soup.jpg',
  'Суп-пюре из тыквы и кабачков': '/img/recipes/pumpkin-zucchini-soup.jpg',
  'Суп с бараниной и овощами': '/img/recipes/lamb-vegetable-soup.jpg',
  'Крем-суп из тыквы': '/img/recipes/creamy-pumpkin-soup.jpg',
  'Суп с курицей и лапшой ширатаки': '/img/recipes/chicken-shirataki-soup.jpg',
  'Борщ кето-версия': '/img/recipes/keto-borscht.jpg',
  'Солянка с мясом': '/img/recipes/solyanka-meat.jpg',
  'Харчо по-грузински': '/img/recipes/georgian-kharcho.jpg',
  'Том ям с креветками': '/img/recipes/tom-yum-shrimp.jpg',
  'Суп с индейкой и овощами': '/img/recipes/turkey-vegetable-soup.jpg',
  'Суп-пюре из цветной капусты': '/img/recipes/cauliflower-puree-soup.jpg',
  'Крем-суп из авокадо': '/img/recipes/creamy-avocado-soup.jpg',
  
  // ГОРЯЧИЕ ВТОРЫЕ (25)
  'Лосось в су-виде с овощами': '/img/recipes/sous-vide-salmon-vegetables.jpg',
  'Куриная грудка на гриле с овощами': '/img/recipes/grilled-chicken-breast-vegetables.jpg',
  'Говядина, запеченная в духовке': '/img/recipes/oven-baked-beef.jpg',
  'Креветки, жаренные на сковороде с чесноком': '/img/recipes/pan-fried-shrimp-garlic.jpg',
  'Стейк из говядины на гриле': '/img/recipes/grilled-beef-steak.jpg',
  'Куриные крылышки, запеченные в духовке': '/img/recipes/oven-baked-chicken-wings.jpg',
  'Лосось, запеченный в фольге': '/img/recipes/foil-baked-salmon.jpg',
  'Говядина, тушенная с овощами': '/img/recipes/braised-beef-vegetables.jpg',
  'Куриные бедра на гриле': '/img/recipes/grilled-chicken-thighs.jpg',
  'Индейка, запеченная с травами': '/img/recipes/herb-roasted-turkey.jpg',
  'Кальмары, жаренные в кляре': '/img/recipes/fried-squid-rings.jpg',
  'Говядина, жаренная на сковороде': '/img/recipes/pan-seared-beef.jpg',
  'Курица в сливочном соусе': '/img/recipes/chicken-creamy-sauce.jpg',
  'Лосось на гриле с овощами': '/img/recipes/grilled-salmon-vegetables.jpg',
  'Баранина, запеченная с розмарином': '/img/recipes/rosemary-roasted-lamb.jpg',
  'Куриная грудка в су-виде': '/img/recipes/sous-vide-chicken-breast.jpg',
  'Говяжьи ребрышки на гриле': '/img/recipes/grilled-beef-ribs.jpg',
  'Индейка, тушенная с овощами': '/img/recipes/braised-turkey-vegetables.jpg',
  'Лосось в аэрогриле': '/img/recipes/air-fried-salmon.jpg',
  'Куриная грудка на пару с овощами': '/img/recipes/steamed-chicken-breast-vegetables.jpg',
  'Куриные грудки, жаренные на сковороде': '/img/recipes/pan-fried-chicken-breasts.jpg',
  'Говядина, запеченная с сыром': '/img/recipes/cheese-topped-baked-beef.jpg',
  'Куриные бедра, тушенные с овощами': '/img/recipes/braised-chicken-thighs-vegetables.jpg',
  'Лосось, жаренный на гриле': '/img/recipes/grilled-salmon-fillet.jpg',
  'Говядина в аэрогриле': '/img/recipes/air-fried-beef.jpg',
  
  // КОНДИТЕРСКИЕ (25)
  'Кето-чизкейк без выпечки': '/img/recipes/keto-no-bake-cheesecake.jpg',
  'Кексы с шоколадом на миндальной муке': '/img/recipes/chocolate-almond-cupcakes.jpg',
  'Мороженое из авокадо и кокоса': '/img/recipes/avocado-coconut-ice-cream.jpg',
  'Печенье из миндальной муки': '/img/recipes/almond-flour-cookies.jpg',
  'Шоколадный мусс из авокадо': '/img/recipes/chocolate-avocado-mousse.jpg',
  'Кето-торт с кремом': '/img/recipes/keto-cream-cake.jpg',
  'Тарталетки с ягодами': '/img/recipes/berry-tartlets.jpg',
  'Шоколадные конфеты без сахара': '/img/recipes/sugar-free-chocolate-truffles.jpg',
  'Пудинг из чиа с ягодами': '/img/recipes/chia-pudding-berries.jpg',
  'Кето-круассаны': '/img/recipes/keto-croissants.jpg',
  'Пирог с ягодами на миндальной муке': '/img/recipes/almond-berry-pie.jpg',
  'Шоколадные брауни кето': '/img/recipes/keto-chocolate-brownies.jpg',
  'Мороженое из кокосового молока': '/img/recipes/coconut-milk-ice-cream.jpg',
  'Печенье с орехами': '/img/recipes/nut-cookies.jpg',
  'Крем-брюле кето-версия': '/img/recipes/keto-creme-brulee.jpg',
  'Торт с кремом и ягодами': '/img/recipes/cream-cake-berries.jpg',
  'Пирожные с кремом': '/img/recipes/keto-cream-puffs.jpg',
  'Шоколадный торт без муки': '/img/recipes/flourless-chocolate-cake.jpg',
  'Тарт с лимоном': '/img/recipes/keto-lemon-tart.jpg',
  'Печенье с шоколадом': '/img/recipes/keto-chocolate-cookies.jpg',
  'Мусс из ягод': '/img/recipes/berry-mousse.jpg',
  'Торт с орехами': '/img/recipes/keto-nut-cake.jpg',
  'Печенье с кокосом': '/img/recipes/coconut-cookies.jpg',
  'Шоколадный фондан': '/img/recipes/keto-chocolate-fondant.jpg',
  'Тарталетки с кремом': '/img/recipes/cream-tartlets.jpg',
  
  // С СЫРОМ ФЕТА (20)
  'Салат с сыром фета и огурцами': '/img/recipes/feta-cucumber-salad.jpg',
  'Запеченная куриная грудка с сыром фета': '/img/recipes/baked-chicken-feta.jpg',
  'Омлет с сыром фета и шпинатом': '/img/recipes/omelet-feta-spinach.jpg',
  'Салат с сыром фета, авокадо и яйцами': '/img/recipes/feta-avocado-egg-salad.jpg',
  'Запеченные кабачки с сыром фета': '/img/recipes/baked-zucchini-feta.jpg',
  'Салат с сыром фета и грецкими орехами': '/img/recipes/feta-walnut-salad.jpg',
  'Фаршированные перцы с сыром фета': '/img/recipes/stuffed-peppers-feta.jpg',
  'Салат с сыром фета и тунцом': '/img/recipes/feta-tuna-salad.jpg',
  'Запеченная рыба с сыром фета': '/img/recipes/baked-fish-feta.jpg',
  'Салат с сыром фета и брокколи': '/img/recipes/feta-broccoli-salad.jpg',
  'Салат с курицей и сыром фета': '/img/recipes/chicken-feta-salad.jpg',
  'Яичница с сыром фета и помидорами': '/img/recipes/scrambled-eggs-feta-tomatoes.jpg',
  'Салат с сыром фета, оливками и рукколой': '/img/recipes/feta-olive-arugula-salad.jpg',
  'Запеченная куриная грудка с сыром фета и шпинатом': '/img/recipes/baked-chicken-feta-spinach.jpg',
  'Салат с сыром фета, авокадо и креветками': '/img/recipes/feta-avocado-shrimp-salad.jpg',
  'Омлет с сыром фета и помидорами': '/img/recipes/omelet-feta-tomatoes.jpg',
  'Салат с сыром фета и свеклой': '/img/recipes/feta-beet-salad.jpg',
  'Запеченные баклажаны с сыром фета': '/img/recipes/baked-eggplant-feta.jpg',
  'Салат с сыром фета и грушей': '/img/recipes/feta-pear-salad.jpg',
  'Сыр фета на гриле с овощами': '/img/recipes/grilled-feta-vegetables.jpg',
  
  // БЛЮДА СУ-ВИД (дополнительные)
  'Говядина в су-виде с овощами': '/img/recipes/sous-vide-beef-vegetables.jpg',
  'Стейк из говядины в су-виде': '/img/recipes/sous-vide-beef-steak.jpg',
  'Индейка в су-виде с овощами': '/img/recipes/sous-vide-turkey-vegetables.jpg',
  'Сёмга в су-виде с овощами': '/img/recipes/sous-vide-salmon-vegetables.jpg',
  'Куриные бедра в су-виде': '/img/recipes/sous-vide-chicken-thighs.jpg',
  'Свинина в су-виде с овощами': '/img/recipes/sous-vide-pork-vegetables.jpg',
  'Баранина в су-виде с овощами': '/img/recipes/sous-vide-lamb-vegetables.jpg',
  'Куриная грудка в су-виде с брокколи': '/img/recipes/sous-vide-chicken-breast-broccoli.jpg',
  'Свиная вырезка в су-виде с кабачками': '/img/recipes/sous-vide-pork-tenderloin-zucchini.jpg',
  'Тунец в су-виде с авокадо': '/img/recipes/sous-vide-tuna-avocado.jpg',
  'Ягненок в су-виде с розмарином': '/img/recipes/sous-vide-lamb-rosemary.jpg',
  'Утка в су-виде с овощами': '/img/recipes/sous-vide-duck-vegetables.jpg',
  
  // БЛЮДА АЭРОГРИЛЬ (дополнительные)
  'Куриные крылышки в аэрогриле': '/img/recipes/air-fry-chicken-wings.jpg',
  'Лосось в аэрогриле с овощами': '/img/recipes/air-fry-salmon-vegetables.jpg',
  'Говядина в аэрогриле с брокколи': '/img/recipes/air-fry-beef-broccoli.jpg',
  'Куриные бедра в аэрогриле': '/img/recipes/air-fry-chicken-thighs.jpg',
  'Креветки в аэрогриле с овощами': '/img/recipes/air-fry-shrimp-vegetables.jpg',
  'Свинина в аэрогриле с кабачками': '/img/recipes/air-fry-pork-zucchini.jpg',
  'Индейка в аэрогриле с овощами': '/img/recipes/air-fry-turkey-vegetables.jpg',
  'Рыбные стейки в аэрогриле': '/img/recipes/air-fry-fish-steaks.jpg',
}

// Функция для получения пути к изображению по названию блюда
export function getMealImage(mealName: string): string | undefined {
  return mealImageMapping[mealName]
}

// Функция для добавления изображений ко всем блюдам
export function addImagesToMeals<T extends { name: string; image?: string }>(meals: T[]): T[] {
  return meals.map(meal => ({
    ...meal,
    image: meal.image || getMealImage(meal.name)
  }))
}

